Split asterisk and close, and resize tabs
PretendoNetwork/Ita-bag pull request #1
Opened 2023-01-22 19:13 UTC by hauntii

This PR does the following:

- Tab bar is now shorter
- Tabs are now longer, but resize properly
- The close button is no longer replaced by an asterisk on saving, it is now separate
- Tabs now have a `saved` property.
- Scrollbars are now themed
- Colors are now variables in css

Preview image:
![image](https://user-images.githubusercontent.com/57009359/213935341-57f46a3d-d479-4001-b518-a33893210279.png)

2023-01-23 03:10 UTC, jonbarrow commented
The tabs were the height they were to account for when the tab bar needed to scroll when too many editors are open. How does the tab bar look when the scroll wheel is showing?

2023-01-23 03:13 UTC, hauntii commented
> The tabs were the height they were to account for when the tab bar needed to scroll when too many editors are open. How does the tab bar look when the scroll wheel is showing?

Like this!
![image](https://user-images.githubusercontent.com/57009359/213959957-972773dc-0885-4b6d-a07d-0620a673e063.png)

2023-01-23 03:38 UTC, jonbarrow commented
Looks good! I'm a little concerned that it's not clear on the scroll bar which section is the thumb vs the background, maybe rounding the thumb a bit would help that?

2023-01-23 03:41 UTC, jonbarrow commented
Also I see you added variables to `app.css` which are then used in multiple other files

`app.css` is supposed to only contain styles for the `app` section of the UI, `index.css` is for global/general styles

2023-01-23 03:43 UTC, jonbarrow commented
I will do a proper code review tomorrow, I see a couple areas I'd like to address

2023-01-23 03:44 UTC, hauntii commented
Fixed the variable thing, here's what a rounded handle looks like on the scrollbar.
Not much of a change, though.
![image](https://user-images.githubusercontent.com/57009359/213962339-081c177b-7d7b-4ce8-ad48-b92e5cc648e7.png)

2023-01-24 15:12 UTC, jonbarrow requested changes
A couple changes need to be made and pushed. Some small, some big

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/app.css
> +	--color-highlight-light: #A185D6;
These variables seem to be used globally. `app.css` is dedicated to styles in the `app` section of the UI, and should only define variables used in that section

Global variables should be defined in `index.css`

Maybe the CSS file could be renamed to be more clear?

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/app.css
> +::-webkit-scrollbar{
Missing space between `::-webkit-scrollbar` and `{`

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/app.css
> +::-webkit-scrollbar-corner { background: var(--color-scroll-dark); }
Inconsistent styling of styles. Some single-style definitions use multiple lines, others like this are on one line

I would like to enforce that all CSS styles must use multi-line blocks even if there's only a single style declared (I'm aware I also did not do thi,s I just now made this decision)

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/file-system.css
> +  background: url('data:image/svg+xml;utf8,<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M3 5C3 3.343
Maybe we should make these SVGs their own files and have the CSS pull from that? So that way we don't have to update the CSS if the SVG icon changes

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/file-system.css
> +  background: url('data:image/svg+xml;utf8,<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" ><path d="M12 6C12.5523 6 13 6.44772 13 7V11H17C17.5523 11 18
Same suggestion as the other SVG review comment

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/css/file-system.css
> +  background-image: url('data:image/svg+xml;utf8,<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M8 11C7.44772 11 7 11.4477 7 12C7 12.5523 7.44
Same suggestion as the other SVG review comment

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/js/prb-editor.js
>  }
See the other comment about saved states

2023-01-24 15:12 UTC, jonbarrow commented on app/assets/js/tabs.js
> +		if (tab.saved == false) {
A file/editors states arenot `saved` and `unsaved`, the states are `modified` and `unmodifed`

The default state is `unmodified`, meaning no asterisk being shown. When the state changes the being `modified` then the UI needs to reflect that change in state

You should not write code that looks for a default state, code should assume the default state and then branch it's functionality based on changes to the default state

By using the states `saved` and `unsaved` in this way you are checking for the default state, which should not be happening. You should only do a check to see if the default state has changed to another state

Also having the default state be called `saved` doesn't make a lot of sense because it implies that changes were made and then were saved, whereas `unmodified` makes perfect sense because when the file is first opened it has the default state, it has not been "saved" when it first opens it just remainds "unmodified"

2023-01-25 00:32 UTC, hauntii commented
Alright, I've resolved the issues. While looking at the CSS, I did find an empty `tabs.css` file. Seems like the tabs should be in there rather than `app.css`, or it be removed. Which do you prefer?

2023-01-25 00:32 UTC, jonbarrow commented
It can be removed. Also the scroll bar styles are global and should be moved to the index file

2023-01-25 00:34 UTC, hauntii commented
Alright, done!

2023-01-25 02:09 UTC, jonbarrow approved these changes

2023-01-25 02:09 UTC, merged