Make upload image buttons functional and fix linting issues
PretendoNetwork/Ita-bag pull request #5
Opened 2023-06-19 19:37 UTC by DaniElectra

We still can't save the PRB file, but having the ability to upload
images is a nice feature. Example:

![image](https://github.com/PretendoNetwork/ita-bag/assets/112760654/d463204c-aa3f-4b07-b57e-fad09617cf37)

Also fix some easily-solvable linting issues.

2023-06-21 20:21 UTC, jonbarrow requested changes

2023-06-21 20:21 UTC, jonbarrow commented on app/assets/js/prb-editor.js
> +		});
This goes for all the image sizes, but maybe an error being thrown if the image isn't the expected size would be more clear instead of nothing happening in the UI?

2023-06-21 20:21 UTC, jonbarrow commented on app/assets/js/tabs.js
> +	if((selectedTab || selectedEditor) == null) { return; }
Space at the `if`

2023-06-21 22:18 UTC, DaniElectra commented on app/assets/js/prb-editor.js
> +		});
I'm using the following code:
```js
if (image.getWidth() !== 32 && image.getHeight() !== 32) {
	throw new Error('Image size is not 32x32!');
}
```

But the error only shows up on the DevTools console. Is that enough?

![image](https://github.com/PretendoNetwork/ita-bag/assets/112760654/38fe50b8-facd-47a4-b196-0696433b64bb)

2023-06-22 01:07 UTC, jonbarrow commented on app/assets/js/prb-editor.js
> +		});
I was thinking more like an `alert` box so the user can visually see there is an issue

2023-06-22 01:08 UTC, hauntii commented on app/assets/js/prb-editor.js
> +		});
While console is always open by default right now, I agree with Jon that an alert box would be better

2023-06-24 05:47 UTC, jonbarrow requested changes

2023-06-24 05:47 UTC, jonbarrow commented on app/assets/js/prb-editor.js
> +		if (image.getWidth() !== 32 && image.getHeight() !== 32) {
Using `&&` here can allow for either the width or the height to not be 32. For example if the width was 64 while the height was 32, then this check fails to catch the invalid image. `||` should be used instead to catch if either are invalid (this occurs in the other 2 image checks as well)

2023-06-24 10:38 UTC, DaniElectra commented on app/assets/js/prb-editor.js
> +		if (image.getWidth() !== 32 && image.getHeight() !== 32) {
Ah right, didn't catch that

2023-06-24 16:42 UTC, jonbarrow approved these changes

2023-06-24 16:42 UTC, merged